spring:
    application:
        name: Yakdabang

    profiles:
        include: secret

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQLDialect
server:
    port: 5001

#sql:
     #   init:
      #      mode: always
       #     schema-locations: classpath:db-script/schema.sql
        #    data-locations: classpath:db-script/data.sql







