spring:
    application:
        name: Yakdabang

    profiles:
        include: secret

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true

    sql:
        init:
            mode: always
            schema-locations: classpath:db-script/schema.sql
            data-locations: classpath:db-script/data.sql







